# Generated by Django 3.1.6 on 2021-02-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroMediuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=60)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
                ('data_nascimento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('fixo', models.CharField(blank=True, max_length=14, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cadastroMediuns',
            },
        ),
    ]
